### ISSUE TITLE
播放器FLV格式支持

### ISSUE THREAD

**Issue by Yukinoshita** [zhaojun1998/zfile-vue#4]
请问可以在dplayer里引入flv.js来支持flv的播放吗？不太熟悉前端，自己尝试修改没有成功

**Comment by zhaojun1998** [comment]
目前已经引入了的，可以播放 FLV 视频的，参考 [DEMO 站](https://zfile.jun6.net/#/main/视频)

**Comment by Yukinoshita** [comment]
再次测试了一下，发现似乎是存储策略导致的问题，使用同一个视频，世纪互联是不能播放的，但本地存储可以
